"""empty message

Revision ID: 14756068c296
Revises: bf7d7a7a631a
Create Date: 2024-09-13 15:38:39.752354

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14756068c296'
down_revision = 'bf7d7a7a631a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('posts_categories',
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='cascade')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('posts_categories')
    # ### end Alembic commands ###
