"""empty message

Revision ID: 19629cb479e1
Revises: 71103a507e4b
Create Date: 2024-09-26 14:38:30.344554

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19629cb479e1'
down_revision = '71103a507e4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('active', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('active')

    # ### end Alembic commands ###
