"""empty message

Revision ID: 71103a507e4b
Revises: cf98e43b1464
Create Date: 2024-09-24 18:44:28.494447

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71103a507e4b'
down_revision = 'cf98e43b1464'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=256), nullable=False),
    sa.Column('upload_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('filename')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('file')
    # ### end Alembic commands ###
