"""empty message

Revision ID: d219140d520f
Revises: bf38751b82c6
Create Date: 2024-09-09 18:23:04.359406

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd219140d520f'
down_revision = 'bf38751b82c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=128), nullable=False))
        batch_op.alter_column('username',
               existing_type=mysql.VARCHAR(length=128),
               nullable=True)
        batch_op.drop_index('eamil')
        batch_op.create_unique_constraint(None, ['email'])
        batch_op.drop_column('eamil')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('eamil', mysql.VARCHAR(length=128), nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_index('eamil', ['eamil'], unique=True)
        batch_op.alter_column('username',
               existing_type=mysql.VARCHAR(length=128),
               nullable=False)
        batch_op.drop_column('email')

    # ### end Alembic commands ###
